variable "vpc_id" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "alb_sg_id" {}
variable "ec2_sg_id" {}
variable "desired_capacity" {}
variable "min_size" {}
variable "max_size" {}
variable "ami_id" {}
variable "init_path" {}