name: Build Infrastructure

on:
  # schedule:
  #   - cron: '0 7 * * 0-4'   # Run at 09:00 AM (Sunday - Thursday)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: IaC

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: IaC

      - name: Apply Terraform (Build Infra)
        run: |
          echo "Applying Terraform to build infrastructure..."
          terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: IaC

      - name: Update ALB DNS in README
        run: ./IaC/scripts/alb_publish.sh
